apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      volumes:
        - name: shared-image
          persistentVolumeClaim:
            claimName: todo-app-claim
      containers:
        - name: todo-app
          image: PROJECT/IMAGE_FE
          livenessProbe:
            httpGet:
              path: /healthz
              port: 5555               
            initialDelaySeconds: 15
            periodSeconds: 20
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /healthz
              port: 5555
            initialDelaySeconds: 10
            periodSeconds: 15
            failureThreshold: 3
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: todo-app-configmap
                  key: port

            - name: TIMEOUT
              valueFrom:
                configMapKeyRef:
                  name: todo-app-configmap
                  key: timeout
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          volumeMounts:
            - name: shared-image
              mountPath: /usr/src/app/static