apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-backend-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app-backend
  # strategy: 
  #   type:  "Recreate"
  template:
    metadata:
      labels:
        app: todo-app-backend
    spec:
      containers:
        - name: todo-app-backend
          image: PROJECT/IMAGE_BE
          livenessProbe:
            httpGet:
              path: /healthz
              port: 5555               
            initialDelaySeconds: 15
            periodSeconds: 20
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /healthz
              port: 5555
            initialDelaySeconds: 10
            periodSeconds: 15
            failureThreshold: 3
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          env:
          - name: NATS_URL
            valueFrom:
              configMapKeyRef:
                name: todo-app-configmap
                key: nats-url
                  
          - name: PORT
            valueFrom:
              configMapKeyRef:
                name: todo-app-configmap
                key: port

          - name: MONGO_PASSWORD
            valueFrom:
              secretKeyRef:
                name: todo-app-secret
                key: mongo_password

          - name: MONGO_USERNAME
            valueFrom:
              configMapKeyRef:
                name: todo-app-configmap
                key: mongo_initdb_root_username

          - name: MONGO_HOST
            value: mongodb-svc

          - name: MONGO_DB
            valueFrom:
              configMapKeyRef:
                name: todo-app-configmap
                key: mongo_initdb_database

