apiVersion: apps/v1
kind: Deployment
metadata:
  name: broadcast-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: broadcaster
  template:
    metadata:
      labels:
        app: broadcaster
    spec:
      containers:  
        - name: broadcaster
          image: PROJECT/IMAGE_BD
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: todo-app-configmap
                  key: port 
            - name: TIMEOUT  
              valueFrom:
                configMapKeyRef:
                  name: todo-app-configmap
                  key: timeout 
            - name: NATS_URL 
              valueFrom:
                configMapKeyRef:
                  name: todo-app-configmap
                  key: nats-url
            - name: DISCORD_WEBHOOK_URL 
              valueFrom:
                secretKeyRef:
                  name: todo-app-secret
                  key: discord-webhook-url
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
