apiVersion: v1
kind: Secret
metadata:
    name: todo-app-secret
data:
    mongo_password: aWRvbnRjYXJl
    discord-webhook-url: "aHR0cHM6Ly9kaXNjb3JkLmNvbS9hcGkvd2ViaG9va3MvMTQwMjcyNjQ5MDAxNzEwMzg4Mi84cHlxdFlXS1IwRnpJcVRpR2pLOG15Z21DT1JrZ1VmcWRKSW1CYmRKR21FRHduT2xVbnhGaDJRaEtJMnUzRnJMRWJsaQ=="
